pipeline {
  agent {
    label "node"
  }
  stages {
    stage('Example') {
      environment {
        SERVICE_CREDS = credentials('my-predefined-username-password')
      }
      steps {
        sh 'echo "Service user is $SERVICE_CREDS_USR"'
        sh 'echo "Service password is $SERVICE_CREDS_PSW"'
        echo "Running URL: ${env.JENKINS_URL} "
      }
    }
    stage("A") {
      steps {
        echo "========executing A========"
      }
      post {
        always {
          echo "========always========"
        }
        success {
          echo "========A executed successfully========"
        }
        failure {
          echo "========A execution failed========"
        }
      }
    }
  }
  post {
    always {
      echo "========always========"
    }
    success {
      echo "========pipeline executed successfully ========"
    }
    failure {
      echo "========pipeline execution failed========"
    }
  }
}